var w = 700;
var h = 700;
var percent = 0;
var sizePartitions = 100;
var partitionsx = [];
var newpartitionsx = [];
var partitionsy = [];
var newpartitionsy = [];
var justStarted = true;
var canvas;
var shufflingx;
var shufflingy;
var sorting;
var bubble = true;
var quick = false;
var sum = true;
let xs = [];
let ys = [];
let xmax;
let ymax;
let shufflebtn;
let sortbtn;
let methodSelect;
let counter = 0;
let condition = 0;
let bubblingx = 1;
let bubblingy = 1;
let image;
let c;